p_0:
  constraint: A < B
  orphan: false
  predicate: p
  streams:
    Y:
      direction: input
      name: y
    Z:
      direction: input
      name: z
  substitutions:
    A: Y
    B: Z
p_1:
  constraint: (all_equal([A,B,C]))
  orphan: false
  predicate: q
  streams:
    V:
      direction: input
      name: v
    W:
      direction: input
      name: w
    X:
      direction: input
      name: x
  substitutions:
    A: V
    B: W
    C: X
