states:
- 0
- 1
- 2
- 3
- 4
- 5
- 6
- 7
initial: 0
accepting:
- 3
- 7
3:
  2: ~p_1 | ~p_2
6:
  2: ~p_1
  4: p_1 & ~p_0 & ~p_2
5:
  2: p_1
  4: ~p_0 & ~p_1 & ~p_2
  5: p_2 & ~p_0 & ~p_1
  7: p_0 & ~p_1 & ~p_2
7:
  2: ~p_2
  6: p_2 & ~p_0
4:
  4: ~p_0 & ~p_2
  5: p_2 & ~p_0
  7: p_0 & ~p_2
0:
  4: ~p_0
  7: p_0
1:
  2: p_1 | ~p_2
  6: p_2 & ~p_0 & ~p_1
2:
  2: 'True'
